/**
 * 8gent Jr - local text-to-speech for web.
 *
 * The web app uses the browser/device SpeechSynthesis engine only. There is no
 * hosted TTS proxy and no third-party voice provider in this runtime path.
 */

export interface TTSOptions {
  /** Text to speak */
  text: string;
  /** Optional local browser voice URI or catalogue hint. Unknown IDs use the system default. */
  voiceId?: string;
  /** Speech rate 0.5-2.0 (default 1.0) */
  rate?: number;
  /** Volume 0.0-1.0 (default 1.0) */
  volume?: number;
  /** Kept for old callers; ignored by local speech. */
  stability?: number;
  /** Kept for old callers; ignored by local speech. */
  similarityBoost?: number;
}

export type TTSEngine = 'browser' | 'none';

let currentUtterance: SpeechSynthesisUtterance | null = null;

export function stopSpeaking(): void {
  if (typeof window !== 'undefined' && window.speechSynthesis) {
    window.speechSynthesis.cancel();
  }
  currentUtterance = null;
}

export function isSpeaking(): boolean {
  return typeof window !== 'undefined' && Boolean(window.speechSynthesis?.speaking);
}

export function getAvailableEngine(): TTSEngine {
  if (typeof window === 'undefined') return 'none';
  return window.speechSynthesis ? 'browser' : 'none';
}

export async function speak(options: TTSOptions): Promise<TTSEngine> {
  const { text, voiceId, rate = 1.0, volume = 1.0 } = options;
  if (!text || typeof window === 'undefined') return 'none';

  stopSpeaking();
  return speakBrowser(text, { voiceId, rate, volume });
}

/**
 * Previous builds preloaded hosted audio. Local browser voices have nothing to
 * preload, but keeping this no-op preserves the public API for existing views.
 */
export function preloadAudio(_words: string[], _voiceId?: string): void {
  // No-op: local SpeechSynthesis is generated by the device at playback time.
}

function speakBrowser(
  text: string,
  opts: { voiceId?: string; rate: number; volume: number }
): Promise<TTSEngine> {
  return new Promise<TTSEngine>((resolve) => {
    if (!window.speechSynthesis) {
      resolve('none');
      return;
    }

    const utterance = new SpeechSynthesisUtterance(text);
    utterance.rate = Math.max(0.5, Math.min(2, opts.rate));
    utterance.volume = Math.max(0, Math.min(1, opts.volume));
    utterance.lang = localVoiceLang(opts.voiceId);

    const voice = findLocalVoice(opts.voiceId, utterance.lang);
    if (voice) utterance.voice = voice;

    currentUtterance = utterance;

    utterance.onend = () => {
      currentUtterance = null;
      resolve('browser');
    };
    utterance.onerror = () => {
      currentUtterance = null;
      resolve('none');
    };

    window.speechSynthesis.speak(utterance);
  });
}

function localVoiceLang(voiceId?: string): string {
  switch (voiceId) {
    case 'system-us':
      return 'en-US';
    case 'system-ie':
    case 'system-gb':
      return 'en-GB';
    default:
      return 'en-GB';
  }
}

function findLocalVoice(voiceId: string | undefined, lang: string): SpeechSynthesisVoice | null {
  const voices = window.speechSynthesis.getVoices();
  if (voices.length === 0) return null;

  if (voiceId && voiceId.startsWith('voice:')) {
    const uri = voiceId.slice('voice:'.length);
    const exact = voices.find((v) => v.voiceURI === uri);
    if (exact) return exact;
  }

  const preferred = voices.find((v) => v.lang.toLowerCase() === lang.toLowerCase());
  if (preferred) return preferred;

  return voices.find((v) => v.lang.toLowerCase().startsWith('en')) ?? null;
}
