import Link from 'next/link';

export const metadata = {
  title: 'Consent link expired',
  robots: { index: false, follow: false },
};

const REASONS: Record<string, string> = {
  invalid: 'The confirmation link was not valid. It may have been altered, or it was not generated by us.',
  used: 'This link has already been used. Consent can only be confirmed once per step.',
  order: 'This step-2 link was clicked before step-1 was confirmed. Please click step-1 first.',
};

export default async function ExpiredPage({
  searchParams,
}: {
  searchParams: Promise<{ reason?: string }>;
}) {
  const params = await searchParams;
  const reason = params.reason && REASONS[params.reason]
    ? REASONS[params.reason]
    : 'This parental-consent link has expired. Consent links are valid for 7 days.';

  return (
    <main className="min-h-dvh flex items-center justify-center px-6"
      style={{ backgroundColor: 'var(--brand-bg)' }}>
      <div className="max-w-md w-full text-center">
        <div className="inline-flex items-center justify-center w-14 h-14 rounded-2xl text-white text-xl font-bold mb-4"
          style={{ backgroundColor: 'var(--brand-accent)' }}>8</div>
        <h1 className="text-2xl font-bold mb-3"
          style={{ color: 'var(--brand-text)', fontFamily: 'var(--font-display)' }}>
          Link expired
        </h1>
        <p className="text-base mb-4" style={{ color: 'var(--brand-text-soft)' }}>
          {reason}
        </p>
        <p className="text-sm mb-6" style={{ color: 'var(--brand-text-muted)' }}>
          You can restart the sign-up flow to receive fresh confirmation emails.
        </p>
        <Link href="/onboarding" className="inline-block px-6 py-3 rounded-xl text-white font-semibold"
          style={{ backgroundColor: 'var(--brand-accent)' }}>
          Start again
        </Link>
      </div>
    </main>
  );
}
